AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Style/Documentation:
  Enabled: false
